### ISSUE TITLE
<root> element required?

### ISSUE THREAD

**Issue by richb-hanover** [isaacs/sax-js#154]
I had been playing with sax-js a while back, and I had code that worked beautifully (and simply) in November 2014. The current (npm 1.1.1) version doesn't work as well - and requires a workaround (see below). 

Here's the situation: My application creates a data stream containing a series of XML records that have this format:

```xml
<KC_version id="0">1.5</KC_version>
<KC_getproperty name="authtypes" id="1"/>
<KC_setproperty name="clientversion" id="2">InterMapper RemoteAccess 5.7.1</KC_setproperty>
<KC_getproperty name="version" id="3"/>
... etc...
```
To demonstrate the problem, place the XML above into the file testcommands.xml then run the program below. If you use the version of sax.js from November 2014 (sorry, I don't know what commit changed the behavior), the output will show one JSON entry per XML record. Using the npm 1.1.1 version, there's a JSON object created by the first XML record, and the remainder of the XML is treated as text. 

I can work around this by creating a Transform that injects "\<root>" at the start of the stream, but this seems like a lot of work. Is there an option that will regain this previous behavior? (I can supply a diff of the two sax.js files.)

```javascript
/***
 * Test to show off changed behavior between 19Nov2014 sax.js and the npm 1.1.1 version
 * 25Jun2015 -reb
 ***/

var saxStream = require('sax').createStream(false, {lowercasetags: true});
saxStream.on("error", function(e) {
    console.log("saxStream got error: " + e);
});
saxStream.on("opentag", function(node) {
    console.log("saxStream got new tag: " + JSON.stringify(node));
});

saxStream.on("closetag", function(tag) {
    console.log("saxStream got closetag: " + tag);
});

saxStream.on("text", function(data) {
    console.log("saxStream got text: " + data);
});

try {
    var fs = require('fs');
    var s = fs.createReadStream('./testcommands.xml');
    s.pipe(saxStream);
}
catch (e){
    console.log("Uh oh..." + e);
}
```
Desired (previous) behavior:
```
saxStream got new tag: {"name":"kc_version","attributes":{"id":"0"},"isSelfClosing":false}
saxStream got text: 1.5
saxStream got closetag: kc_version
saxStream got text: 

saxStream got new tag: {"name":"kc_getproperty","attributes":{"name":"authtypes","id":"1"},"isSelfClosing":true}
saxStream got closetag: kc_getproperty
saxStream got text: 

saxStream got new tag: {"name":"kc_setproperty","attributes":{"name":"clientversion","id":"2"},"isSelfClosing":false}
saxStream got text: InterMapper RemoteAccess 5.7.1
saxStream got closetag: kc_setproperty
saxStream got text: 
...
```
Current (npm 1.1.1) behavior:
```
saxStream got new tag: {"name":"kc_version","attributes":{"id":"0"},"isSelfClosing":false}
saxStream got text: 1.5
saxStream got closetag: kc_version
saxStream got text: 
<KC_getproperty name="authtypes" id="1"/>
<KC_setproperty name="clientversion" id="2">InterMapper RemoteAccess 5.7.1</KC_setproperty>
<KC_getproperty name="version" id="3"/>
...
```

**Comment by richb-hanover** [comment]
Update: The "previous" version that worked was in fact 0.6.1 - d6f66de. 

Is there anyone who could give advice about using the current code 1.1.1 (now 1.1.2) code to make this work without injecting the one-use Transform? Thanks.

**Comment by isaacs** [comment]
What about this workaround?

```javascript
    var fs = require('fs');
    var s = fs.createReadStream('./testcommands.xml');
    saxStream.write('<root>')
    s.pipe(saxStream);
```

The issue is that, per the spec as I understand it, an XML doc needs to have a single root element.  So, whatever comes after the close of the first open tag is actually just rando text, not XML elements.  What you're describing is actually a stream of distinct XML docs.

You can throw a dummy root element in there at the start, and then just throw it away in your parsing logic, which should give you the desired behavior.

**Comment by richb-hanover** [comment]
Hi! Thanks for the response. I agree with your diagnosis - the XML spec and the sax parser both expect a single root element. I  need to think about whether just writing "<root>" into the stream (it's actually a bidirectional tls stream coming from an external server) will do the trick.
 
But most comforting is the that a) this was an intentional change that brings sax-js closer to conformance, and that b) I'm not missing some magical configuration/option that will solve the problem. I'm content with either of these workarounds. Thanks again.

**Comment by richb-hanover** [comment]
Final (working) answer to close the issue. I wasn't sure about whether your workaround (writing to the stream) would work since it's a duplex stream that underlies the saxStream... Instead, I pushed '\<root>' onto the underlying duplex stream, which seems to feed it back to the input of the sax stream. Here's a skeleton of what I did...

````
tls = require('tls');
sax = require('sax');

var svr = tls.connect(port, options, callback);
var saxStream = sax.createStream(false, {lowercasetags: false, trim: true});
// ... set up event listeners for opentag, closetag, text on saxStream for elements that arrive

svr.pipe(saxStream);    // pipe the tls stream into the sax stream 
svr.push('<root>');     // push the <root> element onto the *tls* stream 
                        // (which winds up feeding it back as input to the saxStream)
````
