### ISSUE TITLE
Missing license/notice for String.fromCodePoint

### ISSUE THREAD

**Issue by pombredanne** [isaacs/sax-js#158]
At https://github.com/isaacs/sax-js/blob/d5055a0ec458449c091ae47eb738c439a2688912/lib/sax.js#L1376 there is a vendored copy of this function:
https://github.com/mathiasbynens/String.fromCodePoint/blob/master/fromcodepoint.js

I think it is missing the original license notice at: https://github.com/mathiasbynens/String.fromCodePoint/blob/master/LICENSE-MIT.txt

/HTH

**Comment by isaacs** [comment]
Oops!  You're absolutely right.  Will fix shortly.

**Comment by pombredanne** [comment]
@isaacs thanks: you are a mensch!
