### ISSUE TITLE
Variable to pass in for sax-js method

### ISSUE THREAD

**Issue by mikeyjm145** [isaacs/sax-js#161]
I am looking to use saxjs for xml parsing but sax-js requires itself as a parameter for the entire function. Where do I get this sax parameter from?

**Comment by mikeyjm145** [comment]
More than having an issue with sax not existing, I am having an issue with the pass in for the sax.js function. It requires you to pass in a sax object that have all of those methods existing already. I am not sure where that comes from or what to pass in for that. I am using nodejs 0.12.0. Please clarify how what to pass in and where to get this sax object with all of the existing methods and variables.

**Comment by mikeyjm145** [comment]
**I apologize for I am not sure how to do code tags in comments but here is what Ia m talking about**

;(function (**sax**) {
sax.parser = function (strict, opt) { return new SAXParser(strict, opt) }
sax.SAXParser = SAXParser
sax.SAXStream = SAXStream
sax.createStream = createStream

<h5>The pass here for saxjs is sax. It has the existing objects: parser, SAXParser, SAXStream, createStream. Am I suppose to create an object such as:</h5>

var sax = { parser: null, SAXParser: null, SAXStream: null, createStream: null }

<h5>for the method?</h5>

**Comment by thiakil** [comment]
You need not concern yourself with that wrapping function, look down the bottom of the file, its simply passing module.exports as sax.

so 
```
sax.parser = function (strict, opt) {
```
becomes 
```
module.exports.parser = function (strict, opt) {
```

Just use it how the Usage doc in Readme says.

```
var sax = require("sax");//NB, this is modified, not sure why readme has the internal path
parser = sax.parser(strict, opts);
//or, if you really prefer the new operator syntax
parser = new sax.SAXParser(strict, opt);
```

**Comment by mikeyjm145** [comment]
Thank you for the quick reply. I was able to reach a solution due to:

1. The code is clean and easy to read and understand than some of the other projects that have forked it or used it in their projects such as Node-XML.
2. I did not have to touch any of the core code for this solution.

I apologies for the trouble. It is the first time I have seen such syntax for returning an export. I usually see modules use the syntax:

-(some name) = (anonymous function);
-module.exports = (some name);

Therefore, changed the export method to mirror the way I usually see it done:

*var saxParser* = (function (**removed pass-in**) {
**(created sax pass in with objects needed for parser) -->** var **sax** = { parser: {}, SAXParser: {}, SAXStream: {}, createStream: {} };

**...**
**(Return the sax object via return statement used for access)**
return {
	sax: sax
}

})();

**(Exported as module)**
module.exports = saxParser;

Nonetheless, your module works very well  and keep up the good work. Thank you for giving a brief explanation of the ternary statement at the end of the code.

**Comment by thiakil** [comment]
Why would you even need to modify it?
