### ISSUE TITLE
Space in attribute and double qoutes return incorrect value

### ISSUE THREAD

**Issue by anius** [isaacs/sax-js#170]
I am using sax to parse xml attributes which contain spaces:
```
<section-1>
  <mytag navtitle="Hello world"></mytag>
</section-1>
```

Then
 ```
parser.onattribute = function (attr) {
  console.log('attr ', attr);
};
```
will return wrong values:
```
attr  { name: 'navtitle', value: '\\"Hello' }
attr  { name: 'world', value: 'world' }
```

If I use single quotes in xml everything works fine:
```
<section-1>
  <mytag navtitle='Hello world'></mytag>
</section-1>
```
returns
```
attr  { name: 'navtitle', value: 'Hello world' }
```

Why double quotes and space in attributes cause this kind of behaviour? Is this intended and if it's possible to fix it in some way or maybe I need to use some sax options to disable this bahaviour?

**Comment by isaacs** [comment]
Works for me. https://gist.github.com/isaacs/0502c87ec4616060b0d03d69d9da47ba

Output:

```
$ node p.js
attr  { name: 'NAVTITLE', value: 'hello world' }
```

**Comment by isaacs** [comment]
Are you sure you're using double-quotes and not curly-double-quotes like “ and ” which sometimes online editors swap out?  I see this happen a lot when people copy stuff from StackOverflow or GitHub that isn't properly wrapped in code blocks.
