### ISSUE TITLE
Some functions do not always return a value

### ISSUE THREAD

**Issue by jaystrictor** [isaacs/sax-js#176]
Thank you for this nice project. I use it in a [Gnome Shell Extension](https://github.com/jaystrictor/gnome-shell-extension-syncthing) to parse a config file.

When parsing `sax.js`, the Gjs Javascript engine reports some log messages, that some functions do not always return a value. This is not really a problem, as these are merely warning messages and the parser works fine.

But it is a little bit annoying, as in the long term these warnings clutter the logs. Would it be possible to eradicate these warnings? Thank you very much in advance.

```
Gjs-Message: JS WARNING: [sax.js 45]: function SAXParser does not always return a value
Gjs-Message: JS WARNING: [sax.js 208]: anonymous function does not always return a value
Gjs-Message: JS WARNING: [sax.js 176]: function SAXStream does not always return a value
```

**Comment by isaacs** [comment]
I don't use Gjs, and I generally don't like making arbitrary code changes to accommodate linters if the program is functioning properly.
