### ISSUE TITLE
Parse result of entity replacement

### ISSUE THREAD

**Issue by devongovett** [isaacs/sax-js#199]
The SVG test suite uses custom entities as sort of macros extensively: they define entities in the doctype that have SVG tags in them, and use the entities to insert those tags in multiple places later in the document. For example: http://www.w3.org/Graphics/SVG/Test/20110816/svg/coords-viewattr-01-b.svg.

``` svg
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1 Basic//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11-basic.dtd" [
  <!ENTITY Smile "
    <rect x='.5' y='.5' width='29' height='39' fill='black' stroke='orange' stroke-width='2'/>
    <g transform='translate(0, 5)'>
      <circle cx='15' cy='15' r='10' fill='yellow'/>
      <circle cx='12' cy='12' r='1.5' fill='black'/>
      <circle cx='17' cy='12' r='1.5' fill='black'/>
      <path d='M 10 19 L 15 23 20 19' stroke='black' stroke-width='2'/>
    </g>
  ">
  <!ENTITY Viewport1 "<rect x='.5' y='.5' width='49' height='29' fill='none' stroke='blue'/>">
  <!ENTITY Viewport2 "<rect x='.5' y='.5' width='29' height='59' fill='none' stroke='blue'/>">
]>
```

I'm parsing the custom entities out of the doctype and putting them on `parser.ENTITIES`, but they don't get parsed as XML, they just show up as text. Not sure if that's something you want to support. If not, a way to turn off all entity decoding so I can do it myself would be needed. Happy to write a PR for either, just need some direction.

**Comment by atesgoral** [comment]
Got bitten by the same issue while parsing Wireshark dictionaries.
