### ISSUE TITLE
Stream : Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by 1045922393** [isaacs/sax-js#254]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `sax@1.2.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/sax/lib/sax.js b/node_modules/sax/lib/sax.js
index 795d607..51d879c 100644
--- a/node_modules/sax/lib/sax.js
+++ b/node_modules/sax/lib/sax.js
@@ -218,7 +218,7 @@
       })
     })
   }
-
+  if(!Stream) Stream = function(){}
   SAXStream.prototype = Object.create(Stream.prototype, {
     constructor: {
       value: SAXStream
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by XiaoPiHong** [comment]
I have the same problem.

**Comment by sjors98** [comment]
I have this issue as well when using `aws-sdk` in react-native.
However this issue only seems to happen on Android, not on iOS... 
The patch works for me, but it would be nice if this can be fix in `sax-js` itself :)

**Comment by austinGENEreeve** [comment]
I am running into this issue with react native as well. I am seeing the issue on iOS right now. using as a dependancy of `azure-sdk-for-js`

The answer provided works for now
