### ISSUE TITLE
All caps tag names

### ISSUE THREAD

**Issue by olnoeve** [isaacs/sax-js#37]
When using the loose mode parser with trim set to true, the resulting tag names come back all capitalized. using the lowercasetags: true option, the tag names correctly get turned to lowercase. Are the tags converted to uppercase by default or is there something that I am setting that I am not aware of?

thanks

**Comment by Domvel** [comment]
Over 7 1/2 years later: Why not just keeping the case format? Or split is as separate optional parameter? Non-strict mode is just for non-valid-xml. Nobody expecting the case insensitive tag names in this parameter. ...
